### PR TITLE
Fix for #47

### PR DESCRIPTION
**Pull request by Erik3003**
Changes made for modpack makers...

### CODE REVIEW

**Comment by DaedalusGame** [comment]
why not just make it an empty droplist?

**Comment by Erik3003** [comment]
You would have to edit the mod on every release and ship the edited version. Could also cause problems with Curse-modpacks, because the launcher won't differentiate between an original and edited version, downloading the unedited version for the users...

**Comment by DaedalusGame** [comment]
no, you can make a resource pack for changing loot tables.

**Comment by Erik3003** [comment]
But the user could easily disable the resource pack, by exident :P

**Comment by DaedalusGame** [comment]
don't see how this is a problem, really, same thing can happen with things like configs and minetweaker scripts

**Comment by Erik3003** [comment]
How about servers, they don't have support for texture pack for all I know?

**Comment by DaedalusGame** [comment]
You can set a server resourcepack that can be transmitted to the clients, also loottables should work fine on a server

**Comment by Erik3003** [comment]
Just tried using a resource pack, but it didn't work... Loot tables don't update...

**Comment by Erik3003** [comment]
http://pastebin.com/4yM6QdjH
This is the new loot table (just for testing), but the gearbox still drops gold nuggets on destructon

**Comment by DaedalusGame** [comment]
Okay I checked online because it wasn't working for me either, and apparently they go in your world folder. I think issue #47 will need another read.

**Comment by Erik3003** [comment]
Sadly that ALT doesn't work either... tried betterwithmods/block/gearbox.json, betterwithmods/chests/gearbox.json and betterwithmods/loot_tables/block/gearbox.json

**Comment by BeetoGuy** [comment]
I'm sort of wondering exactly how viable the loot tables would be, myself. Maybe there should be a config option or a MineTweaker method to edit those drops, the loot tables were a sort of "quick and cheap" solution. I'll merge this anyway, it might be beneficial for modpack makers.

**Comment by DaedalusGame** [comment]
Could use the interaction recipes that are already in for the kiln and the turntable, but on a seperate recipe handler.

**Pull request merged**
