### PR TITLE
Pulley movement is now more smooth

### PR DESCRIPTION
**Pull request by MRebhan**
This should fix most of the pulley fall through and stuck player issues
I also made the platform model look better with the new textures
And you derped a bit with the pulley textures but all fixed ;)

### CODE REVIEW

**Comment by MRebhan** [comment]
Wait, don't merge yet - changes incoming!

**Comment by MRebhan** [comment]
This is taking longer than expected - don't worry it'll come!

**Comment by BeetoGuy** [comment]
It's fine, take your time.

**Comment by MRebhan** [comment]
Yeah, I'll need it, transferring all platform blocks into a single entity instead of 1 per block and keeping bounding boxes up is very hard

I did that because sometimes not all the platform entities get sent to the client for whatever reason and also overhead

**Comment by MRebhan** [comment]
My "fix" for the api update to keep compatibility with the older api is this, it replaces the addTrait() method on the first line:

        //hellfire.addTrait(TinkerMaterials.autosmelt);
        Object autosmelt = null;
        try {
			try { // try loading the new API class
				autosmelt = TinkerMaterials.class.getClassLoader().loadClass("slimeknights.tconstruct.tools.TinkerTraits").getField("autosmelt").get(null);
			} catch (IllegalArgumentException | IllegalAccessException e) {
				e.printStackTrace();
			}
		} catch (ClassNotFoundException | NoSuchFieldException e) {
			try { // fallback
				autosmelt = TinkerMaterials.class.getField("autosmelt").get(null);
			} catch (IllegalArgumentException | IllegalAccessException | NoSuchFieldException | SecurityException e1) {
				e.printStackTrace();
			}
			e.printStackTrace();
		} catch (SecurityException e) {
			e.printStackTrace();
		}
        
        if (autosmelt != null) {
        	hellfire.addTrait((ITrait) autosmelt);
        }

**Comment by MRebhan** [comment]
I have not found any more bugs with the new system, you can pull! :)

**Comment by BeetoGuy** [comment]
Oh man, that's a lot smoother. Nice work, dude.

**Comment by MRebhan** [comment]
Thanks! Also everyone says "multiple bounding boxes per entity is impossible"
I've just proven them wrong. :D

**Pull request merged**
