### PR TITLE
Fixed sloped rails breaking when moved with the pulley

### PR DESCRIPTION
**Pull request by MRebhan**

### CODE REVIEW

**Comment by MRebhan** [comment]
woops don't pull just yet >.<

**Comment by BeetoGuy** [comment]
Looks good. Would you be able to take a look at the issues I commented on in the last pull request, before I merge this?

**Comment by MRebhan** [comment]
Of course!

**Comment by MRebhan** [comment]
I've fixed most of the stuff now, but one more thing remains unfortunately, related to saving/loading. So don't pull just yet, but try out the new build at my repo please!

**Comment by MRebhan** [comment]
So two more bugs I've discovered and then it's ready for pull!

**Comment by MRebhan** [comment]
Looks like it's fixed now. Please note that all worlds created before this patch are incompatible with the new one, it may crash and burn (or not). :P

**Comment by MRebhan** [comment]
Now the moving platform entity isn't saved in the world directly, but in the pulley tile entity! I'm pretty proud of that

**Comment by BeetoGuy** [comment]
Very nice.

**Comment by MRebhan** [comment]
Also, you might want to bump the version since pulleys are a pretty big change ;)

**Comment by BeetoGuy** [comment]
Oh yeah, definitely.

**Comment by MRebhan** [comment]
Wait, don't pull just yet ;)

**Pull request merged**
