### PR TITLE
Pulleys!

### PR DESCRIPTION
**Pull request by MRebhan**
Added: 
 - Pulley
 - Platform

(With crafting recipes!)

You will have to fix inventory rendering for those items though, it's not working
And maybe change the pulley textures and side of platform, it's BTW's original and doesn't really fit with BWM

### CODE REVIEW

**Comment by MRebhan** [comment]
Also, the Pulley and Platform don't appear in JEI. (Maybe related to it not rendering correctly in the inventory?)

**Comment by DaedalusGame** [comment]
Kinda looks like you didn't register an item model for your block in the client proxy. Pretty sure JEI doesn't show items with no valid item model.

**Comment by MRebhan** [comment]
Yep, that's it. Thanks!

**Comment by BeetoGuy** [comment]
Looks good. I'll work on textures after the merge.

**Comment by MRebhan** [comment]
Darn. You were too quick, I noticed a bug with rails.
Oh well, I'll just make a new PR :P

**Comment by BeetoGuy** [comment]
Yeah, I've noticed a few things that might not be working right. Seems there's still a chance you'll fall through the platform when descending, and the platform just stops ascending at Y 16 for some reason.

**Comment by MRebhan** [comment]
Yeah, the Y movement on the platform is really stupid. Maybe it's better now.
Looking into the second issue now. Really strange

**Comment by MRebhan** [comment]
Don't really know why that's happening. Trying another approach now where all the platform blocks are "riding" the rope, might take a while
that should also fix the block desync issue that sometimes happens

**Pull request merged**
