### PR TITLE
[Incomplete&Experimental] First pass of updating to 1.11.

### PR DESCRIPTION
**Pull request by Koward**
Many changes happened and I have not tracked them all, plus Forge itself is still changing. One that's a bit tricky is that ItemStacks can't be null anymore, now we should check the "null" stack that is in a stack field of ItemStack. I'm trying to snipe them all but this will need a lot of testing.
Of course mod integration is completely untouched since nobody is on 1.11 yet there's nothing we can do about that ATM.

### CODE REVIEW

**Comment by primetoxinz** [comment]
if you could fix the conflicts and change it to the 1.11 branch that would be nice

**Comment by Koward** [comment]
I cannot create new branches. This requires a writer access. Once the branch is created, I will of course switch to it ;) .
The conflicts will be solved tomorrow I was just away for a couple days.

**Comment by primetoxinz** [comment]
I already created the 1.11 branch

**Comment by Koward** [comment]
Yes I have only seen it seconds after my message, sorry, it's switched.

**Pull request merged**
