### PR TITLE
[WIP] Hardcore Smelting

### PR DESCRIPTION
**Pull request by blueyu2**
Note: ASM Patches only work when the mod is compiled. If there is a way for ASM to work when launching in a dev environment, I do not know it.

Changes cook times for various items, such as ore and sand
Changes burn times for logs

Issues:
MineTweaker integration does not work
JEI lists all logs burning for 1600 ticks, when different logs have different burning times

### CODE REVIEW

**Comment by Koward** [comment]
Would a new custom furnace cause that much work compared to ASM ? It would be more robust for updates (even tho there would still be some copypasta and reflection, but there is with the ASM way too).
We could test it in dev environment. As well as expanding/improving it more easily in the future.

**Comment by DaedalusGame** [comment]
But if somebody else overrides the furnace, bad things will happen. But it's the same way with ASM really... Really wish forge's fuel value hook would trigger as the first methodcall instead of the last.

**Comment by Koward** [comment]
The worse thing that can happen is somebody else replacing the vanilla recipe with its custom furnace too, we'll get a recipe conflict but that will be far more obvious to see and to fix than anything that happens with bytecode editing. And even before any fix users of MineTweaker for example would already be able to choose if they want our furnace, the other or both. So I believe that's not really a bad thing.

The existing hooks (for custom mod items) would still work as I guess we would keep using the TileEntityFurnace.getItemBurnTime() untouched as the default time, that's already in this PR.
I also wish the hook allowed to override vanilla items burntimes. Though, we still need more things like consuming the fuel immediately and overriding getCookTime() so a custom furnace would still be a solid plan.

**Comment by primetoxinz** [comment]
Closing this as it's too far behind to revive easily and likely not possible

**Pull request closed without merging**
