### PR TITLE
[WIP] More refactoring & bug fixes. + Forge updates

### PR DESCRIPTION
**Pull request by Koward**
There are various optimizations and small refactoring to update more easily when API change. I also kept it updated to Forge 21120 (and ATM mappings 3/11).
Anchor also uses the fantastic 1.9 multipart model system to lower the model count and simplify the JSON.

### CODE REVIEW

**Comment by BeetoGuy** [comment]
I'm pretty sure those SideOnly annotations were added to prevent it crashing serverside.

**Comment by Koward** [comment]
Hi !
* @SideOnly does not prevent to be called serverside, it just scraps the method/class/field but no reference. If it's called somewhere, some kind of NotFoundException. Where I removed them we still get this exception as it ends up calling a Mojang SideOnly. I can bring it back (and "propagate" it to all methods calling in the end a Mojang SideOnly) but I fail to see why as we would get the same error anyway ? Of course if needed I can bring it back without problem.
* The getMinimumPower() was not used anywhere, so if anyone was to implement a machine using it it was to be ignored, but I will bring it back in the next commit =) !

**Comment by BeetoGuy** [comment]
Yeah, the server's still crashing, saying that it can't find IStateMapper during item registration.

**Comment by Koward** [comment]
Okay I have been stupid and I did not think about the class loading all imports even when not calling the method. A solution (to avoid runtime deleting) would be different classes for client but the structure would be awful to use. Adding @SideOnly() where this could happen right now. I apologize.

**Pull request merged**
