### PR TITLE
[WIP] Vessel of the Dragon

### PR DESCRIPTION
**Pull request by blueyu2**
Issues
- Sync issue when loading world
- XP contained gets reset to 0 when receiving mechanical power

### CODE REVIEW

**Comment by Koward** [comment]
Could this have the rendering performance problem of the Cooking Pot (mentioned line 463 and at issue #102 ) ? At the time I think BeetoGuy wanted to move it out in a separate block, but it's always a painful operation (to avoid breaking worlds).

**Comment by BeetoGuy** [comment]
Yeah, I think the conclusion was that the block would be created when the Vessel of the Dragon was added, then move the crucible and cauldron over to that one and removing the rotation state from the old block. And yeah, I think it would be more readable if those facing variables used EnumFacing instead.

**Comment by blueyu2** [comment]
So, should I close this and work on a cooking pot overhaul instead?

**Comment by primetoxinz** [comment]
There is now a vessel of the dragon in the game, although nonfunctional. if you want to implement on that go for it

**Pull request closed without merging**
