### PR TITLE
Added Diamond Ingots

### PR DESCRIPTION
**Pull request by blueyu2**
Added config option to change diamond tools and armor to use diamond ingots, and adds recycling recipes.

### CODE REVIEW

**Comment by DaedalusGame** [comment]
http://i.imgur.com/4aiTO2U.png

**Comment by blueyu2** [comment]
@DaedalusGame Is that the texture you want to use for the diamond ingot instead?

**Comment by DaedalusGame** [comment]
Your call, I submitted it to primetoxin back when he was still working on a decompiled version. If you think it looks good you can take it

**Comment by meelock** [comment]
I made a diamond ingot that has a creeper face on it, I can upload it if you want.

**Comment by DaedalusGame** [comment]
Diamond Ingot design contest woo

**Comment by blueyu2** [comment]
Perhaps have a third party be the judge? like Beeto or prime?

**Comment by primetoxinz** [comment]
sure, I'll judge

**Comment by meelock** [comment]
[Here is my (i called it diamantine) diamond ingot](http://imgur.com/ucgJBej) for a mod that I made.

**Comment by primetoxinz** [comment]
well, I think the @DaedalusGame's texture is more unique and keeps it different from the original mod

**Comment by meelock** [comment]
Also @blueyu2 I would recommend haveing diamond ingots be crafted in a stoked crucible, as I feel diamonds should be as late game or later game then soul steel.

**Comment by DaedalusGame** [comment]
1. Without diamond and if Hardcore Buckets works as it does in BTW, you have a very very very very very hard time getting to the nether
2. You can easily make a crucible without fighting the ender dragon

**Comment by blueyu2** [comment]
Perhaps in an unstoked cauldron? I remember BTWTweaks changing the recipe to require a cauldron.

**Comment by meelock** [comment]
It's actually not that hard as i have found, as water still pours. It just takes a few trips.

**Comment by DaedalusGame** [comment]
In BTW, you cannot pick lava up in a bucket.

**Comment by meelock** [comment]
last i checked that wasnt the case, but i may be wrong.

**Comment by primetoxinz** [comment]
in BTW the original mod you cannot pick up lava, in BTM you can because it was forgotten

**Pull request merged**
